
package com.lac.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://ws.lac.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserService {


    /**
     * 
     * @param user
     * @throws UserRunTimeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.AddResponse")
    public void add(
        @WebParam(name = "user", targetNamespace = "")
        User user)
        throws UserRunTimeException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.lac.ws.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.ListResponse")
    public List<User> list();

    /**
     * 
     * @param username
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.DeleteResponse")
    public void delete(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.lac.ws.User
     * @throws UserRunTimeException_Exception
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.lac.com", className = "com.lac.ws.LoginResponse")
    public User login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws UserRunTimeException_Exception
    ;

}
