
package com.lac.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserService", targetNamespace = "http://ws.lac.com", wsdlLocation = "file:/C:/Users/flyapple88/AppData/Local/Temp/tempdir7396210706103449147.tmp/us_1.wsdl")
//@HandlerChain(file="handler-chain.xml")
public class UserService
    extends Service
{

    private final static URL USERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lac.ws.UserService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lac.ws.UserService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/flyapple88/AppData/Local/Temp/tempdir7396210706103449147.tmp/us_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/flyapple88/AppData/Local/Temp/tempdir7396210706103449147.tmp/us_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERSERVICE_WSDL_LOCATION = url;
    }

    public UserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserService() {
        super(USERSERVICE_WSDL_LOCATION, new QName("http://ws.lac.com", "UserService"));
    }

    /**
     * 
     * @return
     *     returns IUserService
     */
    @WebEndpoint(name = "userServicePort")
    public IUserService getUserServicePort() {
        return super.getPort(new QName("http://ws.lac.com", "userServicePort"), IUserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUserService
     */
    @WebEndpoint(name = "userServicePort")
    public IUserService getUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lac.com", "userServicePort"), IUserService.class, features);
    }

}
