
package com.lac.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DMSService", targetNamespace = "http://service.hao24.dms", wsdlLocation = "http://172.168.1.201:8080/axis2/services/DMSService")
public class DMSService
    extends Service
{

    private final static URL DMSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lac.ws.DMSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lac.ws.DMSService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:7001/ld/proxy/ldbizproxy");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.168.1.201:8080/axis2/services/DMSService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DMSSERVICE_WSDL_LOCATION = url;
    }

    public DMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMSService() {
        super(DMSSERVICE_WSDL_LOCATION, new QName("http://service.hao24.dms", "DMSService"));
    }

    /**
     * 
     * @return
     *     returns DMSServicePortType
     */
    @WebEndpoint(name = "DMSServiceHttpSoap11Endpoint")
    public DMSServicePortType getDMSServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.hao24.dms", "DMSServiceHttpSoap11Endpoint"), DMSServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DMSServicePortType
     */
    @WebEndpoint(name = "DMSServiceHttpSoap11Endpoint")
    public DMSServicePortType getDMSServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hao24.dms", "DMSServiceHttpSoap11Endpoint"), DMSServicePortType.class, features);
    }

}
