
package com.lac.ws;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DMSServicePortType", targetNamespace = "http://service.hao24.dms")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DMSServicePortType {


    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendRunCostBillToLD", action = "urn:RequestSendRunCostBillToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendRunCostBillToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendRunCostBillToLD")
    @ResponseWrapper(localName = "RequestSendRunCostBillToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendRunCostBillToLDResponse")
    public String requestSendRunCostBillToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestOrderStateToLD", action = "urn:RequestOrderStateToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestOrderStateToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestOrderStateToLD")
    @ResponseWrapper(localName = "RequestOrderStateToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestOrderStateToLDResponse")
    public String requestOrderStateToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param args
     */
    @WebMethod(action = "urn:main")
    @Oneway
    @RequestWrapper(localName = "main", targetNamespace = "http://service.hao24.dms", className = "com.lac.Main")
    public void main(
        @WebParam(name = "args", targetNamespace = "http://service.hao24.dms")
        List<String> args);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendErrorBillToLD", action = "urn:RequestSendErrorBillToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendErrorBillToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendErrorBillToLD")
    @ResponseWrapper(localName = "RequestSendErrorBillToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendErrorBillToLDResponse")
    public String requestSendErrorBillToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendADebitToLD", action = "urn:RequestSendADebitToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendADebitToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendADebitToLD")
    @ResponseWrapper(localName = "RequestSendADebitToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendADebitToLDResponse")
    public String requestSendADebitToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendTReplCostBillToLD", action = "urn:RequestSendTReplCostBillToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendTReplCostBillToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendTReplCostBillToLD")
    @ResponseWrapper(localName = "RequestSendTReplCostBillToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendTReplCostBillToLDResponse")
    public String requestSendTReplCostBillToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendReplCostBillToLD", action = "urn:RequestSendReplCostBillToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendReplCostBillToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendReplCostBillToLD")
    @ResponseWrapper(localName = "RequestSendReplCostBillToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendReplCostBillToLDResponse")
    public String requestSendReplCostBillToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendErrorToLD", action = "urn:RequestSendErrorToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendErrorToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendErrorToLD")
    @ResponseWrapper(localName = "RequestSendErrorToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendErrorToLDResponse")
    public String requestSendErrorToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendKSErrorToLD", action = "urn:RequestSendKSErrorToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendKSErrorToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendKSErrorToLD")
    @ResponseWrapper(localName = "RequestSendKSErrorToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendKSErrorToLDResponse")
    public String requestSendKSErrorToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestSendRewardBillToLD", action = "urn:RequestSendRewardBillToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestSendRewardBillToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendRewardBillToLD")
    @ResponseWrapper(localName = "RequestSendRewardBillToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestSendRewardBillToLDResponse")
    public String requestSendRewardBillToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestOrderFlowToLD", action = "urn:RequestOrderFlowToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestOrderFlowToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestOrderFlowToLD")
    @ResponseWrapper(localName = "RequestOrderFlowToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestOrderFlowToLDResponse")
    public String requestOrderFlowToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

    /**
     * 
     * @param cs
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestDelveryInfoToLD", action = "urn:RequestDelveryInfoToLD")
    @WebResult(targetNamespace = "http://service.hao24.dms")
    @RequestWrapper(localName = "RequestDelveryInfoToLD", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestDelveryInfoToLD")
    @ResponseWrapper(localName = "RequestDelveryInfoToLDResponse", targetNamespace = "http://service.hao24.dms", className = "com.lac.RequestDelveryInfoToLDResponse")
    public String requestDelveryInfoToLD(
        @WebParam(name = "CS", targetNamespace = "http://service.hao24.dms")
        String cs);

}
